language: ruby
rvm:
- 2.2.5
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
branches:
  only:
  - master
install:
- bundle install
script:
- bundle exec jekyll build
- timeout 240s bundle exec htmlproofer ./_site --check-html --check-favicon --allow-hash-href
  --external_only --only-4xx --http-status-ignore 429
after_success: s3_website push
notifications:
  slack:
    rooms:
      - secure: k4yoaAk2mcXdG7Vj5Bjk0RTBvgJd+qt3+VUimDPCr/xShXnxfU9IgqnNe+a4tJfLM+yWxO5XjEXCW+XF8CaseSfSPeTiXWZGHe6inGMOuKVOaIjRQdQz8pt55JakmfdRG3WgGRdfQkFI7aeRR7muhUn/M7562S1fRtHUESxIO4NFrykB8S+tnXUPqhwf0fy+6UylT1hwtNUDtDBzfRkU4gKDponfeb7wb2Bq/+nyCGSaPmorMA4hVmFVaPvqTXvd0tAd2ieQXVnPZyOR6mQuC2DtcKE8IdT8Bvrv3/viR0kk3GuwjQv/u3Vke4xJXGMqPPlIv7h8ed/3yF4DVoXXn2Bpxcp2P6gEaGUbm7iIZfq5ykMIX/XcoMpEn06PiGZKQivNOY/STKESz2pEBscgRa6wvdviTjgZ3YSUK3T25wl93EKL9t/rjqWF7EjNH1G4rFxp+/Rb6mq5iegM/tlDdC6/QDG725N49cpGpJs76Vf1yRlcBo9U7OgbEG7qGGSVwW7ICZfjbTZmM/pZDMgaMUEZKe+URCBGSvZPH8uh/ztGe1x+XyOU9PJU51Iy6th80PlOBej6kaeSiBpEAYHF+ljDf6sEMjAi5DqYxL0oDJO6IQ4Eas4vAdvQofDZJfjgxjMy+9cSt0PraGNdIm5c4uxXX0NF3bhfGJMphTn6mnI=
    on_success: always
