language: ruby
rvm:
- 2.2.5
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
branches:
  only:
  - master
install:
- bundle install
script:
- bundle exec jekyll build
- timeout 240s bundle exec htmlproofer ./_site --check-html --check-favicon --allow-hash-href
  --external_only --only-4xx --http-status-ignore 429
after_success: s3_website push
notifications:
  slack:
    secure: EnL9YOsP4GzIufzxBW33F/EEu1irhQ6OCAhkRGPduh9pi1J5TCcV6jqdQv1weCNdIJJiUqZqheNrfTj9rw8PXkqBExZllNa6m7CedfHrk6u42wu8VZwW2KhLrlLwDldsUwtE15IWavjzzX7/4A3CkXoLqOhBi8u6JpV/2hPMDRe7KyM4wxWWJJkhsKIDmA5C9eekMJH3iztdjAdeqzqBFF2Jo/gc9B7m5eybVBAESHvSgv2GGFgCFzLqfKQ5RbWk7pQFf/DveUpxYaRyT27askP2tNBb++I8gKhk7gZlIDQ6GtfTZBxhB/5b2C+ItJlFT/XvuW8VGVI+KQLPh6ydyLXtwQJ46eoyezuy8JN/yLBgwHCadzJ9UJySLJOyKyDg7MomHAfuZfj2v+Isveb5IoHqkwXB9kQLE6Ya8G0v+v1XNXMax4iQvk4YvM02S2ChOidh+AOQs7n9cxenXLYGI6+hD+z7xWiaAP652XrZIKgeOEsLATZL69xM5E4qsXjQvtu6dGMH4fDRozQr3v15J/EBoywBRbbbgun68E6y0cTx8wLEaGHi8a+XzlqGv8D05TjKMKdr4rd7xuXKYlW6d7SvbVaPPZQz5Slu0OwvQsNEtQsNSuwmzfGDaT9B0+6+wbag8UrnokZxicpQHpxea6dsUUZs5ghywrLnLLrFrHw=
    on_success: always
