language: ruby
rvm:
- 2.2.5
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
branches:
  only:
  - master
install:
- bundle install
script:
- bundle exec jekyll build
- timeout 240s bundle exec htmlproofer ./_site --check-html --check-favicon --allow-hash-href
  --external_only --only-4xx --http-status-ignore 429
after_success: s3_website push
notifications:
  slack:
    secure: NLxdGrc9/ZUgUQiKjUIQfjuCD8kiviTGfwDK0y0SPXnFkGe1WbzdJKwSdTMyMoQiJH4UcTQKiG3UyJDtquXj4SHLLpc7L/0Z1N34vbr5EcfQXwDivnz+gfaS6XJLtU3q4pPLcO9twzyrVw1cqa2zBOTv7XedoWyLqp7pTl3Cr0AU5MFDkauX8uPpJbXYwyDqGODeFV6KRxNZ7QX6dCFKu3iIMTg9MfnoVXl/TJM/0lDjWmn7S06FS2VCgwGlkEmNc1RwShVJZIqyxuSW3Sg4Hl7IzfnGFjt6uN0aKlT6uP2vJLVTOHpVw/1qfZPtSD1GSri6/7mGo9Zt3fx5wB8yH4/FO0ziJsajYG1bqrtDyRAVADLgPv7QI2Gl6u1KD78NqAU8zVuo/s8gsZiahjPGaeY7rWWaMiV/NqcozYifPvri8KnhrztXa6+1qGg8OIGglq7fiwbKBbQGFBGzzsr8OG0rDTadyu4d9uhELhvKUqq3TxUHHK3LbwMX5tXU+yy5v5F5ZLrBP17Ye1YBCUjp48HOe14CL/BV5whxYsHnB/m6XFZmcTwoUUG885EYNKrrC6Lt2edYaajjdOtfk3SmqQS94sCJf1nL0Fh2ruF10PRAyb0t10Pxq1K25DfNRPg8n3pDK/lKIuOY4dR4OuiXitinVqyoa9ZFzom0y36TXMY=
    on_success: always
